In [1]:
import numpy as np
import random

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
a = np.array([i for i in range(1,11)], dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
m = 5
n = 5

a = np.array(([random.randint(1, 10) for _ in range(m * n)]), dtype=int)
b = a.reshape(m, n)
print(b)

[[10  7  5  4  3]
 [10  3  5 10  8]
 [ 1  7  2  3  6]
 [ 5  9  9  3 10]
 [ 9  1 10 10 10]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
m = 4
n = 4

a = np.array(([random.uniform(0.0, 1.0) for _ in range(m * n)]), dtype=float)
b = a.reshape(m, n)
print(b)

[[0.15910514 0.08209474 0.42736903 0.80480011]
 [0.09495236 0.17763116 0.32217246 0.72617075]
 [0.2077647  0.68726204 0.78693222 0.94453491]
 [0.37621409 0.95211253 0.66645398 0.25971385]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
n = 5

a = np.array([random.randint(1, 10) for _ in range(n)])
b = np.array([random.randint(1, 10) for _ in range(n)])

print('a:', a)
print('b:', b)
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)

a: [1 1 8 2 5]
b: [7 4 8 3 8]
a + b: [ 8  5 16  5 13]
a - b: [-6 -3  0 -1 -3]
a * b: [ 7  4 64  6 40]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
n = 7

a = np.array([random.randint(1, 5) for _ in range(n)])
b = np.array([random.randint(1, 5) for _ in range(n)])
print(a, b, sep='\n')
print ('Скалярний добуток векторів: ', np.dot(a, b))

[4 2 3 3 3 2 3]
[4 4 2 1 1 3 1]
Скалярний добуток векторів:  45


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a = np.array([random.randint(1, 10) for _ in range(4)])
a = a.reshape(2, 2)
b = np.array([random.randint(1, 10) for _ in range(6)])
b = b.reshape(2, 3)
print(a, b, sep='\n')
с = np.dot(a, b)
print ('Добуток матриць: ', с, sep='\n')

[[8 7]
 [3 1]]
[[2 2 1]
 [9 7 1]]
Добуток матриць: 
[[79 65 15]
 [15 13  4]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
m = 3
a = np.array([random.randint(1, 10) for _ in range(m * m)])
a = a.reshape(m, m)
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.14210526 -0.11578947  0.08421053]
 [ 0.04736842  0.29473684 -0.30526316]
 [-0.16315789 -0.12631579  0.27368421]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
m = 4
a = np.array([random.uniform(0.0, 1.0) for _ in range(m * m)])
a = a.reshape(m, m)
print('Вихідна матриця:', a, sep='\n')
print('Транспонована матриця:', a.T, sep='\n')

Вихідна матриця:
[[0.56751209 0.63721974 0.93346898 0.67724418]
 [0.68923913 0.54452505 0.74548528 0.0771147 ]
 [0.49968104 0.33703179 0.11795492 0.35399293]
 [0.06688333 0.53589614 0.95730997 0.75528452]]
Транспонована матриця:
[[0.56751209 0.68923913 0.49968104 0.06688333]
 [0.63721974 0.54452505 0.33703179 0.53589614]
 [0.93346898 0.74548528 0.11795492 0.95730997]
 [0.67724418 0.0771147  0.35399293 0.75528452]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
a = np.array([random.randint(1, 10) for _ in range(12)])
a = a.reshape(3, 4)
print('Матриця А:', a, sep='\n')
b = np.array([random.randint(1, 11) for _ in range(4)])
print('Вектор b:', b, sep='\n')
c = np.dot(a, b)
print('Добуток А на b:', c, sep='\n')

Матриця А:
[[ 8  3  8  6]
 [ 9  1  9 10]
 [ 3  7  8  6]]
Вектор b:
[2 8 2 3]
Добуток А на b:
[74 74 96]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
a = np.array([random.uniform(0.0, 1.0) for _ in range(6)])
a = a.reshape(2, 3)
print('Матриця А:', a, sep='\n')
b = np.array([random.uniform(0.0, 1.0) for _ in range(3)])
print('Вектор b:', b, sep='\n')
c = np.dot(a, b)
print('Добуток А на b:', c, sep='\n')

Матриця А:
[[0.6709929  0.03300303 0.82950699]
 [0.72817546 0.86395738 0.36387843]]
Вектор b:
[0.38466359 0.59466284 0.48859535]
Добуток А на b:
[0.68302547 0.97165525]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
m = 2
a = np.random.randint(1, 11, (m, m))
print('Матриця А:', a, sep='\n')
b = np.random.randint(1, 11, (m, m))
print('Матриця B:', b, sep='\n')
c = a * b
print('Поелементне множення А на B:', c, sep='\n')

Матриця А:
[[3 2]
 [6 6]]
Матриця B:
[[1 7]
 [9 9]]
Поелементне множення А на B:
[[ 3 14]
 [54 54]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
m = 2
a = np.random.randint(1, 11, (m, m))
print('Матриця А:', a, sep='\n')
b = np.random.randint(1, 11, (m, m))
print('Матриця B:', b, sep='\n')
c = np.dot(a, b)
print('Добуток А на B:', c, sep='\n')

Матриця А:
[[ 4  1]
 [ 2 10]]
Матриця B:
[[5 2]
 [9 9]]
Добуток А на B:
[[ 29  17]
 [100  94]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
m = 5
a = np.random.randint(1, 100, (m, m))
print('Матриця А:', a, sep='\n')
print('Сума елементів матриці:', a.sum(), sep='\n')

Матриця А:
[[41 60  6 66 86]
 [63 59 27 90 69]
 [93 15 61 75 49]
 [60 65 34 18 99]
 [64 31 19 79 93]]
Сума елементів матриці:
1422


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
m = 4
a = np.random.randint(1, 10, (m, m))
print('Матриця А:', a, sep='\n')
b = np.random.randint(1, 10, (m, m))
print('Матриця B:', b, sep='\n')
print('Різниця матриць А і В:', a - b, sep='\n')

Матриця А:
[[9 7 6 5]
 [6 7 3 9]
 [7 2 9 1]
 [3 2 2 5]]
Матриця B:
[[3 7 2 5]
 [2 8 4 7]
 [2 5 9 5]
 [2 8 1 5]]
Різниця матриць А і В:
[[ 6  0  4  0]
 [ 4 -1 -1  2]
 [ 5 -3  0 -4]
 [ 1 -6  1  0]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
m = 3
a = np.random.rand(m, m)
print('Матриця А:', a, sep='\n')
row_sums = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:', row_sums, sep='\n')

Матриця А:
[[0.47245139 0.85804543 0.75347027]
 [0.28735259 0.46954618 0.03006951]
 [0.73810449 0.53061642 0.03868319]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
[[2.0839671 ]
 [0.78696827]
 [1.3074041 ]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
m = 3
n = 4
a = np.random.randint(1, 10, (m, n))
print('Початкова матриця:', a, sep='\n')
squared_matrix = np.square(a)
print("Матриця з квадратами чисел початкової матриці:", squared_matrix, sep='\n')

Початкова матриця:
[[2 2 4 9]
 [1 4 3 8]
 [3 2 7 4]]
Матриця з квадратами чисел початкової матриці:
[[ 4  4 16 81]
 [ 1 16  9 64]
 [ 9  4 49 16]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
m = 4
vector_a = np.random.randint(1, 50, m)
print('Початковий вектор:', vector_a, sep='\n')
sqrt_vector = np.sqrt(vector_a)
print("Вектор з квадратними коренями чисел початкового вектора:", sqrt_vector, sep='\n')

Початковий вектор:
[48 14 19 32]
Вектор з квадратними коренями чисел початкового вектора:
[6.92820323 3.74165739 4.35889894 5.65685425]
